/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_assignment1;

import javax.swing.JOptionPane;

/**
 *
 * @author themi
 */
public class choices extends javax.swing.JFrame {

    /**
     * Creates new form choices
     */
    public choices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        normal = new javax.swing.JButton();
        MoveNumber = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TimeLimit = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(881, 775));
        getContentPane().setLayout(null);

        normal.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        normal.setText("Normal game");
        normal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalActionPerformed(evt);
            }
        });
        getContentPane().add(normal);
        normal.setBounds(470, 340, 370, 50);

        MoveNumber.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        MoveNumber.setText("Maximum Moves Limit");
        MoveNumber.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MoveNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveNumberActionPerformed(evt);
            }
        });
        getContentPane().add(MoveNumber);
        MoveNumber.setBounds(470, 420, 370, 50);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Start the Game with :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(510, 200, 330, 70);

        TimeLimit.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        TimeLimit.setText("Time limit");
        TimeLimit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TimeLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeLimitActionPerformed(evt);
            }
        });
        getContentPane().add(TimeLimit);
        TimeLimit.setBounds(470, 260, 370, 50);

        Exit.setFont(new java.awt.Font("Showcard Gothic", 2, 24)); // NOI18N
        Exit.setText("Exit");
        Exit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(470, 500, 370, 50);

        Back.setFont(new java.awt.Font("Showcard Gothic", 3, 24)); // NOI18N
        Back.setText("Back");
        Back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(470, 580, 370, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/choices.jpg"))); // NOI18N
        jLabel1.setText("P3b");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 880, 890);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TimeLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeLimitActionPerformed
        // TODO add your handling code here:
           Puzzle p = new Puzzle();
                     p.show();

        p.timeR.setText("Target:"+"  "+"05:00");
        p.TLimit();
        

                    dispose();

        
       /*  PlayerName pn = new PlayerName();
        
            pn.show();
        */
      
       // p.show();
      
     
    }//GEN-LAST:event_TimeLimitActionPerformed

    private void MoveNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveNumberActionPerformed
        // TODO add your handling code here:
        
                  //  JOptionPane.showMessageDialog(this, "you have to win the game with the minimum number of moves that we given!","Kids Puzzle Game",JOptionPane.);
    
                  
        Puzzle p = new Puzzle();
        p.show();

       // p.show();
        dispose();
        
        p.moveLimit.setText("Target"+"  "+"500");
        p.MLimit();
        

        
    }//GEN-LAST:event_MoveNumberActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalActionPerformed
        // TODO add your handling code here:
           Puzzle p = new Puzzle();
        p.show();
        
        dispose();
    }//GEN-LAST:event_normalActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Rules r=new Rules();
        r.show();
        
        dispose();
        
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new choices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Exit;
    private javax.swing.JButton MoveNumber;
    private javax.swing.JButton TimeLimit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton normal;
    // End of variables declaration//GEN-END:variables
}
