/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_assignment1;

import javax.swing.JFrame;

/**
 *
 * @author themi
 */
public class PlayerName extends javax.swing.JFrame {
    public static String playerName;

    /**
     * Creates new form PlayerName
     */
    public PlayerName() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        UserName = new javax.swing.JTextField();
        NextButton = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        UserNameLable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(860, 720));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("  EnterYour Name:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 210, 360, 70);

        UserName.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });
        getContentPane().add(UserName);
        UserName.setBounds(470, 330, 370, 70);

        NextButton.setBackground(new java.awt.Color(204, 255, 255));
        NextButton.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        NextButton.setForeground(new java.awt.Color(0, 0, 102));
        NextButton.setText("Next");
        NextButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NextButton);
        NextButton.setBounds(670, 540, 150, 60);

        Back.setBackground(new java.awt.Color(204, 255, 255));
        Back.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(0, 0, 102));
        Back.setText("Back");
        Back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back.setBorderPainted(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back);
        Back.setBounds(500, 540, 150, 60);

        UserNameLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Player name1.jpg"))); // NOI18N
        UserNameLable.setText("P2N");
        getContentPane().add(UserNameLable);
        UserNameLable.setBounds(0, 0, 850, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

     public void closeFrame() {
        dispose(); // Dispose the frame
    }
    
    
    
    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:
        
     
        
        
            playerName = UserName.getText();
    
                Rules r =new Rules();
        
                  r.show();
                  
                   OOP_Assignment1.StopMusic();
    
    // Start another music
    OOP_Assignment1.PlayMusic("wav/no_copyright_music_cute_background_music_funny_Pick!!128k.wav");


            
   /* Puzzle p = new Puzzle();
        
        p.show();
    */
       
        dispose();
    }//GEN-LAST:event_NextButtonActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        GameName gm =  new GameName();
        gm.show();
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerName.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerName().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton NextButton;
    public javax.swing.JTextField UserName;
    private javax.swing.JLabel UserNameLable;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
