/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_assignment1;

import java.awt.event.ActionEvent;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.util.TimerTask;
import javax.swing.Timer;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.*;


/**
 *
 * @author themi
 */
public class Puzzle extends javax.swing.JFrame {
        private PlayerName playerNameFrame;

     private int moveCount = 0;
     private int seconds = 0;
     private int minutes = 0;
     public Timer timer;
      
    /**
     * Creates new form Puzzle
     */
    public Puzzle() {
       
        initComponents();
                startTimer();

    }
    
    public void startTimer() {
        
    timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            seconds++;
            if (seconds == 60) {
                seconds = 0;
                minutes++;
            }
            
            updateTimeLabel();
        }
    });
    timer.start();
    
}
    
    
    public void updateTimeLabel() {
 
    timee.setText(String.format("%02d:%02d", minutes, seconds));
    
}
    public void TLimit() {
        timer.stop();                   //to stop the previouse normal game timer.
        seconds = 0;                    //update the timee label
        minutes = 0;
        
        updateTimeLabel();
        
        // Start a new timer with a limit 
        timer = new Timer(1000, new ActionListener() {
            
            public void actionPerformed(ActionEvent e) {
                seconds++;
                 if (seconds == 60) {
                seconds = 0;
                minutes++;
                 }
                
                if (seconds == 0 && minutes == 05) {
                    timer.stop();

                    JOptionPane.showMessageDialog(Puzzle.this, "Time's up!");
                    timee.setText("00:00");
                      dispose();
                    JOptionPane.showMessageDialog(Puzzle.this, "you lose the game.");

                    Again a= new Again();
                    a.show();

                }
                updateTimeLabel();
            }
        });
        timer.start();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        movesLable = new javax.swing.JLabel();
        TimeLable = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        MovesNum = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        timee = new javax.swing.JLabel();
        moveLimit = new javax.swing.JLabel();
        HelpLable = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Help = new javax.swing.JButton();
        timeR = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(670, 835));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(620, 820));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        b1.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        b1.setText("1");
        b1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        b2.setText("2");
        b2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        b3.setText("3");
        b3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        b4.setText("4");
        b4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        b8.setText("8");
        b8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        b7.setText("7");
        b7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        b6.setText("6");
        b6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        b5.setText("5");
        b5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        b9.setText("9");
        b9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b10.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        b10.setText("10");
        b10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        b11.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        b11.setText("11");
        b11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b12.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        b12.setText("12");
        b12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });

        b16.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        b16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });

        b15.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        b15.setText("15");
        b15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });

        b14.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        b14.setText("14");
        b14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });

        b13.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        b13.setText("13");
        b13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(b16, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b16, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 440));

        movesLable.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        movesLable.setForeground(new java.awt.Color(255, 255, 255));
        movesLable.setText("MOVES:");
        jPanel1.add(movesLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 100, 57));

        TimeLable.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        TimeLable.setForeground(new java.awt.Color(255, 255, 255));
        TimeLable.setText("Time:");
        jPanel1.add(TimeLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 630, 92, 63));
        jPanel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 86, -1, -1));
        jPanel1.add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 67, -1, -1));
        jPanel1.add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 583, -1, -1));

        MovesNum.setBackground(new java.awt.Color(102, 102, 0));
        MovesNum.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        MovesNum.setForeground(new java.awt.Color(255, 255, 255));
        MovesNum.setText("00");
        jPanel1.add(MovesNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 100, 63));
        jPanel1.add(filler4, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 606, -1, -1));

        timee.setBackground(new java.awt.Color(102, 102, 0));
        timee.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        timee.setForeground(new java.awt.Color(255, 255, 255));
        timee.setText("0");
        jPanel1.add(timee, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, 90, 60));

        moveLimit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        moveLimit.setForeground(new java.awt.Color(255, 255, 255));
        moveLimit.setText("0");
        jPanel1.add(moveLimit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 680, 150, 50));

        HelpLable.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        HelpLable.setForeground(new java.awt.Color(255, 255, 255));
        HelpLable.setText("Auto Solve:");
        jPanel1.add(HelpLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 740, 140, 52));

        jButton1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jButton1.setText("reset tiles");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 750, 160, -1));

        Help.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Help.setText("Help!");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });
        jPanel1.add(Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 740, 86, 46));

        timeR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        timeR.setForeground(new java.awt.Color(255, 255, 255));
        timeR.setText("0");
        jPanel1.add(timeR, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 680, 140, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/puzzle 2.jpg"))); // NOI18N
        jLabel2.setText("p2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -20, 870, 850));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 810);
        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void changing () {           //changing the numbers when the game is starting...................................................................................
    int[] bn = new int[15];
    int i,j;
    boolean ch =false;
    
       Random rnd = new Random();     

    
    if (ch == false){

       // for (i=1;i<=15;i++){
           
         for(j=0;j<15;j++){
            int num;
            do {
                num = rnd.nextInt(15) + 1;
            } while (contains(bn, num));                   // to don't have same numbers .
            bn[j] = num;           
         }
        //}
       ch= true;
    }
    else{
        ch=false;
    }
            //System.out.println("bn"+bn[1]);
         b1.setText(Integer.toString(bn[0]));
         b2.setText(Integer.toString(bn[1]));
         b3.setText(Integer.toString(bn[2]));
         b4.setText(Integer.toString(bn[3]));
         b5.setText(Integer.toString(bn[4]));
         b6.setText(Integer.toString(bn[5]));
         b7.setText(Integer.toString(bn[6]));
         b8.setText(Integer.toString(bn[7]));
         b9.setText(Integer.toString(bn[8]));
         b10.setText(Integer.toString(bn[9]));
         b11.setText(Integer.toString(bn[10]));
         b12.setText(Integer.toString(bn[11]));
         b13.setText(Integer.toString(bn[12]));
         b14.setText(Integer.toString(bn[13]));
         b15.setText(Integer.toString(bn[14]));
         b16.setText("");
   // ch = false;
}
    private boolean contains(int[] arr, int Val) {
    for (int value : arr) {
        if (value == Val) {
            return true;
        }
    }
            
    return false;

}
    
    
    public void swapping (JButton but1,JButton but2){
     
        if(but2.getText() == ""){
            
            but2.setText(but1.getText());
            but1.setText("");
         moveCount++;
         MovesNum.setText(Integer.toString(moveCount));
   
        }
        
    }
    
    public void WinningState(){                     // identifying the winning state to send the message that the user win the game.
    
        String W1 = b1.getText();
        String W2 = b2.getText();
        String W3 = b3.getText();
        String W4 = b4.getText();
        String W5 = b5.getText();
        String W6 = b6.getText();
        String W7 = b7.getText();
        String W8 = b8.getText();
        String W9 = b9.getText();
        String W10= b10.getText();
        String W11= b11.getText();
        String W12= b12.getText();
        String W13= b13.getText();
        String W14= b14.getText();
        String W15= b15.getText();
        String W16= b16.getText();
        
        if(W1=="1"&&W2=="2"&&W3=="3"&&W4=="4"&&W5=="5"&&W6=="6"&&W7=="7"&&W8=="8"&&
           W9=="9"&&W10=="10"&&W11=="11"&&W12=="12"&&W13=="13"&&W14=="14"&&W15=="15"){
            
            timer.stop();
           
           
            
            Board b =new Board();
            
            b.show();
            
            
            End();


          //  JOptionPane.showMessageDialog(this, "Congragulations you won the game!\n","Kids Puzzle Game",JOptionPane.NO_OPTION);
         //   JOptionPane.showMessageDialog(this, "Thankyou for gamming with us!!","Kids Puzzle Game",JOptionPane.NO_OPTION);
           
            
            timee.setText("00:00");

   
          
        }
    
}

    public void MLimit(){
        int Max = 500;
      //  moveCount++;

        if (moveCount >= Max){
                timer.stop();
                JOptionPane.showMessageDialog(this, "running out of moves","Kids Puzzle Game",JOptionPane.NO_OPTION);
                
                Again a = new Again();
             
               a.show();
                             dispose();

            
        }
        
    }
        
    public void End(){   
        
        
        
       // PlayerName pn = new PlayerName();
        String name = PlayerName.playerName;
        String timeString = timee.getText();
        
        String[] timeParts = timeString.split(":");
        int minutes = Integer.parseInt(timeParts[0]);
        int seconds = Integer.parseInt(timeParts[1]);
        int totalTimeInSeconds = minutes * 60 + seconds;    
        
        System.out.println("final time -> "+totalTimeInSeconds);
        System.out.println("name"+name);
        try {
       FileWriter w = new FileWriter("t1.txt", true); // Append mode
       try(BufferedWriter bf = new BufferedWriter(w) ){
                   bf.write(totalTimeInSeconds + "  :  " + name + "\n");

       }
        System.out.println("Data successfully written to the file.");
    } catch (IOException e) {
        e.printStackTrace();
        System.out.println("An error occurred while writing to the file.");
   
    }
        
                              
                PlayerName pl =new PlayerName();
                pl.show();
                
                pl.dispose();
  
                dispose();

        
    }
    
  
   
    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
        // TODO add your handling code here:                                            //swap the buttons when they click the number buttons.
         swapping(b16,b9);
         swapping(b16,b15);
         
    }//GEN-LAST:event_b16ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
         swapping(b1,b2);
         swapping(b1,b8);
         WinningState();
         MLimit();
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
         swapping(b2,b3);
         swapping(b2,b7);
         swapping(b2,b1);
         WinningState();
          MLimit();
         
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
         swapping(b3,b4);
         swapping(b3,b6);
         swapping(b3,b2);
         WinningState();
          MLimit();
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
         swapping(b4,b5);
         swapping(b4,b3);
         WinningState();
          MLimit();
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
         swapping(b5,b4);
         swapping(b5,b6);
         swapping(b5,b12);
         WinningState();
          MLimit();
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
         swapping(b6,b3);
         swapping(b6,b7);
         swapping(b6,b5);
         swapping(b6,b11);
         WinningState();
          MLimit();
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
         swapping(b7,b2);
         swapping(b7,b8);
         swapping(b7,b6);
         swapping(b7,b10);
         WinningState();
          MLimit();
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
         swapping(b8,b1);
         swapping(b8,b7);
         swapping(b8,b9);
         WinningState();
          MLimit();
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
         swapping(b9,b16);
         swapping(b9,b10);
         swapping(b9,b8);
         WinningState();
          MLimit();
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
         swapping(b10,b7);
         swapping(b10,b9);
         swapping(b10,b11);
         swapping(b10,b15);
         WinningState();
          MLimit();
    }//GEN-LAST:event_b10ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        // TODO add your handling code here:
         swapping(b11,b6);
         swapping(b11,b10);
         swapping(b11,b14);
         swapping(b11,b12);
         WinningState();
          MLimit();
    }//GEN-LAST:event_b11ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        // TODO add your handling code here:
         swapping(b12,b5);
         swapping(b12,b13);
         swapping(b12,b11);
         WinningState();
          MLimit();
    }//GEN-LAST:event_b12ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        // TODO add your handling code here:
         swapping(b13,b12);
         swapping(b13,b14);
         WinningState();
          MLimit();
    }//GEN-LAST:event_b13ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
        // TODO add your handling code here:
         swapping(b14,b15);
         swapping(b14,b13);
         swapping(b14,b11);
         WinningState();
          MLimit();
    }//GEN-LAST:event_b14ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
        // TODO add your handling code here:
         swapping(b15,b10);
         swapping(b15,b16);
         swapping(b15,b14);
         WinningState();
          MLimit();
    }//GEN-LAST:event_b15ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        changing();                                                             // change the numbers when the window is open.
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:                                    // this is for check the code only......................................................................
        b1.setText("1");                                                    // to check the winning state.
        b2.setText("2");
        b3.setText("3");
        b4.setText("4");
        b5.setText("5");
        b6.setText("6");
        b7.setText("7");
        b8.setText("8");
        b9.setText("9");
        b10.setText("10");
        b11.setText("11");
        b12.setText("12");
        b13.setText("13");
        b14.setText("14");
        b15.setText("15");
        b16.setText("");
              WinningState();
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puzzle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Help;
    private javax.swing.JLabel HelpLable;
    public javax.swing.JLabel MovesNum;
    private javax.swing.JLabel TimeLable;
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel moveLimit;
    private javax.swing.JLabel movesLable;
    public javax.swing.JLabel timeR;
    public javax.swing.JLabel timee;
    // End of variables declaration//GEN-END:variables
}
